### ISSUE TITLE
Telepat add admin error: No hostname was set

### ISSUE THREAD

**Issue by aaronfranco** [telepat-io/telepat-cli#1]
I'm not sure what i'm missing here, but I have the entire Telepat infrastructure up and running on Docker. When I try to add a new Admin to Telepat I get the following error:

````
➜  telepat-docker-compose-files git:(master) ✗ telepat add admin --email aaron@test.com --password xyz
No hostname was set
````
I attempted to use the "set" command to fix this issue, but I was unsuccessful.
````
➜  telepat-docker-compose-files git:(master) ✗ telepat set hostname 192.168.99.100                                
hostname value set to: 192.168.99.100
➜  telepat-docker-compose-files git:(master) ✗ telepat configure hostname
hostname is an unknown action for configure
````

**Comment by andreimarinescu** [comment]
Sorry about the bad docs on the CLI, we're working on them.

You should do the following: 

    telepat set telepat_host 192.167.99.100
    telepat set telepat_port 3000

Perhaps this helps as well: http://docs.telepat.io/intro.html

**Comment by aaronfranco** [comment]
Cool, thanks for the fast reply!  Issue resolved.

I am following that guide :+1:
